apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: lab3-pipelinerun
spec:
  pipelineRef:
    name: lab2-pipeline
  params:
    - name: repo-url
      value: https://github.com/ibm-developer-skills-network/ttwst-jhxyb-ci-cd-pipeline_js.git
    - name: branch
      value: main
    - name: message
      value: "Lab 3 pipeline starting"
