apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ci-task
spec:
  steps:
    - name: install-dependencies
      image: node:18
      script: |
        npm ci

    - name: run-tests
      image: node:18
      script: |
        npm test
